server:
  port: 8761
  address: 192.168.61.252

spring:
  application:
    name: DiscoveryService
#  cloud:
#    config:
#      uri: http://192.168.61.252:8888
#      name: ecommerce

eureka:
  client:
    register-with-eureka: false # 나자신은 등록하지 않음
    fetch-registry: false # 마이크로 서비스 인스턴스 목록을 로컬에 캐시할 것인지의 여부
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    ip-address: ${server.address}
#    instance-id: ${server.address}:${server.port}
